### ISSUE TITLE
Go through Trello and pull over content to GitHub Issues

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/equity-data-handbook#10]
Pull content over from our [Trello Board](https://trello.com/b/UQsbotBM/research-for-guidance-team), then archive/delete the board

**Comment by AHolder1** [comment]
After each to do is pulled over - recommend change share settings so no one can view the link or add a note at the top of the doc stating that this is an old link and a more up to date version can be found
[here](https://github.com/CAWaterBoardDataCenter/equity-data-handbook/issues)...or maybe we just delete the Trello Board altogether?

**Comment by DevanBurke** [comment]
All content from Trello has either been completed or already carried over. Trello board related to the Equity Handbook has also been closed!
