### ISSUE TITLE
Organize Best Practices Page

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/equity-data-handbook#13]
[Best Practices Page](https://cawaterboarddatacenter.github.io/equity-data-handbook/best-practice.html)

Move bullets at the bottom of the page into associated section of the page (e.g. move the 1st bullet about using the best available science into either the [Plan & Prepare](https://cawaterboarddatacenter.github.io/equity-data-handbook/best-practice.html#plan-prepare) or [Collect & Process](https://cawaterboarddatacenter.github.io/equity-data-handbook/best-practice.html#collect-process) section - whichever makes the most sense.

**Comment by NMartorano** [comment]
I took a bit of a stab at this but there were a lot of gaps.

**Comment by AHolder1** [comment]
I love it! We can keep building them out as we continue to flesh out the Handbook.
