### ISSUE TITLE
Add City/State Examples to Handbook

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/equity-data-handbook#19]
Other Examples 

- [ ] City of Portland Racial Equity Toolkit: https://www.portlandoregon.gov/oehr/71685 

 
State of California Guidance 

- [ ] Governor Executive Order on Racial Equity: https://www.gov.ca.gov/wp-content/uploads/2022/09/9.13.22-EO-N-16-22-Equity.pdf?emrc=c11513  
- [ ] CalTrans: CONSIDERING EQUITY IN COMMUNITY IMPACT ANALYSIS FOR PROJECTS   https://dot.ca.gov/-/media/dot-media/programs/environmental-analysis/documents/ser/equity-guidance-a11y.pdf 
- [ ] Document showing how a team at the Water Boards used last year’s Governor proposed budget (January budget) to derive challenge questions: https://docs.google.com/document/d/18kJKTQjR39_PhLLQXejKZcuZAY5sD4dFNpV9bfAtqKA/edit?usp=sharing
- [ ] OEHHA paper on CalEnviroScreen 4.0 and how race and ethnicity is analyzed within that tool and the CES score correlations: https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40raceanalysisf2021.pdf 
- [ ] (Internal at this point) CDFW and CNRA resource: [Web-based tools REPORT DRAFT 2.17.23.docx](https://cawaterboards-my.sharepoint.com/:w:/g/personal/greg_gearheart_waterboards_ca_gov/EZ9xso_GAI5OtkjKoZM-dtUBjljjPjFFvZz5txsWQUKpyA?e=5FOemo) 
- [ ] Equity in the State Revolving Fund use for infrastructure:  https://www.policyinnovation.org/publications/a-fairer-funding-stream

**Comment by NMartorano** [comment]
[City of Oakland | OakDOT Geographic Equity Toolbox (oaklandca.gov)](https://www.oaklandca.gov/resources/oakdot-geographic-equity-toolbox) 

 

Pierce County Finance (Washington) utilizes an [Equity Index mapping tool](http://www.piercecountywa.gov/equityindex) to help inform diversity, equity, and inclusion considerations throughout County decision-making. As we continue this work, we are interested in learning more about equity mapping and equity data tools used by other organizations. 

 

The City of Seattle has a Racial and Social Equity Index that many departments use for prioritization and evaluation/analysis. The URL is https://maps.seattle.gov/RSEIndex, it has a [user guide](https://www.seattle.gov/Documents/Departments/OPCD/Demographics/RacialSocialEquityIndexUsersGuide2023.pdf), it was developed and is maintained in-house by our Office of Planning and Community Development, and a good follow-up contact if you have more questions is Diana Canzoneri ([diana.canzoneri@seattle.gov](mailto:diana.canzoneri@seattle.gov)), our City Demographer. 

 

 [EquityNYC](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequity.nyc.gov%2F&data=05%7C01%7Cnicholas.martorano%40waterboards.ca.gov%7C87a614b2e3db4c85368c08dbc55a8595%7Cfe186a257d4941e6994105d2281d36c1%7C0%7C0%7C638320764855634179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r%2Br4%2BybTh130ovhG12PjYHQYqVHlz4jSB8gXj3KTnAI%3D&reserved=0), New York City government's online interactive equity data tool r[ecently launched some new features and our most recent round of data](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmailchi.mp%2F0c99aaff21c4%2Fnew-data-and-features-on-equitynyc09-26%3Fe%3D18425bf7a1&data=05%7C01%7Cnicholas.martorano%40waterboards.ca.gov%7C87a614b2e3db4c85368c08dbc55a8595%7Cfe186a257d4941e6994105d2281d36c1%7C0%7C0%7C638320764855634179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HOhQf9TRABto%2Bmu%2B5q6lW8ALvk%2B1XPS3t5JbO3weoe4%3D&reserved=0). You can click through to learn more about new functionalities and metrics that have been added to v3.0. To answer your prompts:  

Public url:  https://equity.nyc.gov/ 

Mapping Equity: [equity.nyc.gov/mapping-equity](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequity.nyc.gov%2Fmapping-equity&data=05%7C01%7Cnicholas.martorano%40waterboards.ca.gov%7C87a614b2e3db4c85368c08dbc55a8595%7Cfe186a257d4941e6994105d2281d36c1%7C0%7C0%7C638320764855634179%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9M2lNb%2FfFUuFty3WM9oYs97snhKj1T8n8nIj3vXIGOs%3D&reserved=0)

**Comment by NMartorano** [comment]
Added to the Resources Page
