### ISSUE TITLE
Go through OneNote and pull over content to GitHub Issues

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/equity-data-handbook#2]
The resources and other information that would be worth incorporating in my opinion would be in this One Note section [Web Resources for Guidance and Best Practice](onenote:https://cawaterboards-my.sharepoint.com/personal/greg_gearheart_waterboards_ca_gov/Documents/REDAP%20Team%20Notes%20and%20Resources/Web%20Resources%20for%20Guidance%20and%20Best%20Practice.one#&section-id=2ecba4f8-5bc7-4d84-9780-a0bfd2729ebe&end)  ([Web view](https://cawaterboards-my.sharepoint.com/personal/greg_gearheart_waterboards_ca_gov/_layouts/15/Doc.aspx?sourcedoc=%7Bb26ff2c3-af7e-4be5-b579-33ba46615b85%7D&action=edit&wd=target%28Web%20Resources%20for%20Guidance%20and%20Best%20Practice.one%7C2ecba4f8-5bc7-4d84-9780-a0bfd2729ebe%2F%29&wdorigin=717&wdpreservelink=1))

**Comment by NMartorano** [comment]
National Level Guidance 

https://www.census.gov/programs-surveys/acs/data.html  - The American Community Survey (ACS) releases new data every year through a variety of data tables that you can access with different data tools.   

https://www.census.gov/programs-surveys/acs/library/handbook  - You can use American Community Survey (ACS) data in different ways and for different reasons. Each one of our downloadable PDF handbooks helps a particular group with specific how-to instructions and/or case studies. 

 

US EPA has [this public facing guidance](https://www.epa.gov/geospatial/guidance-content-item-metadata-arcgis-online) for content item metadata in ArcGIS Online. 

 

US EPA guidance for Assessing Environmental Justice in Regulatory Analysis  https://www.epa.gov/system/files/documents/2023-11/ejtg_revision_110823_508compliant_0.pdf  

 

Guide from the U.S. Department of Health and Human Services on how to conduct an equity assessment of a policy or program: [In-Depth Equity Assessment Guide | ASPE (hhs.gov)](https://aspe.hhs.gov/reports/equity-assessment-guide) 

 

FACT SHEET: Biden-⁠Harris Administration Releases Annual Agency Equity Action Plans to Further Advance Racial Equity and Support for Underserved Communities Through the Federal Government 

https://www.whitehouse.gov/briefing-room/statements-releases/2024/02/14/fact-sheet-biden-harris-administration-releases-annual-agency-equity-action-plans-to-further-advance-racial-equity-and-support-for-underserved-communities-through-the-federal-government/ 

 

 

 

https://www.usich.gov/resources/uploads/asset_library/Racial_Equity_Data_Guidebook.pdf (link broken?)  - The U.S. Interagency Council on Homelessness (USICH) is the only federal agency with a sole mission focused on preventing and ending homelessness in America. The council consists of 19 federal agencies that help create and catalyze implementation of the Federal Strategic Plan to Prevent and End Homelessness. 

 

https://www.whitehouse.gov/wp-content/uploads/2022/04/eo13985-vision-for-equitable-data.pdf  - From the White House Equitable Data Working Group 

 

https://cssp.org/wp-content/uploads/2021/09/Our-Identities-Ourselves-Project-Infographic-FINAL.pdf - Center for the Study of Social Policy.   This is the first phase of a larger project whose goal is to share best practices for collecting data about race, ethnicity, and other demographic information including sexual orientation, gender identity and expression (SOGIE); national origin; language spoken; disability; religion; and tribal affiliation in child welfare agencies nationwide. 

 

CDC guidance: 

"Principles for Using Public Health Data to Drive Equity A guide to embedding equitable practices throughout the data life cycle"  

 

https://www.cdcfoundation.org/data-equity-principles?inline  

[Federal Register :: Initial Proposals For Updating OMB's Race and Ethnicity Statistical Standards](https://www.federalregister.gov/documents/2023/01/27/2023-01635/initial-proposals-for-updating-ombs-race-and-ethnicity-statistical-standards) 

 

Actionable Intelligence for Social Policy (AISP) Centering for Equity Toolkit: https://aisp.upenn.edu/resource-article/a-toolkit-for-centering-racial-equity-throughout-data-integration/ 

 

Urban Institute's Principles for Advancing Equitable Data Practice: https://www.urban.org/sites/default/files/publication/102346/principles-for-advancing-equitable-data-practice.pdf 

 

General Data Management resource hub from the National Institute of Health that includes FAIR principles, metadata practices etc. https://sharing.nih.gov/data-management-and-sharing-policy/data-management  

 

Hero Database with Racial Equity Resources collated from the National :  https://hero.epa.gov/hero/index.cfm/project/page/project_id/3611  

  

https://nationalequityatlas.org/ The National Equity Atlas is America's most detailed report card on racial and economic equity.

**Comment by NMartorano** [comment]
Data Ethics/Data Sovereignty 

 GovOps medium article on Data Ethics (https://medium.com/caldata/practical-data-ethics-summary-of-what-were-learning-24d0e9d89cd0) 

 

Federal data ethics framework (https://resources.data.gov/assets/documents/fds-data-ethics-framework.pdf)  

 

Operationalizing the CARE and FAIR Principles for Indigenous data futures: 

 https://www.nature.com/articles/s41597-021-00892-0 

 

The Data Ethics Canvas is designed to help identify potential ethical issues associated with a data project or activity. It promotes understanding and debate around the foundation, intention and potential impact of any piece of work, and helps identify the steps needed to act ethically: https://directory.civictech.guide/listing/the-odis-data-ethics-canvas  

 

Ethics Framework (CalData): https://medium.com/caldata/practical-data-ethics-summary-of-what-were-learning-24d0e9d89cd0 ; Framework at a Glance: https://drive.google.com/file/d/14Hl6i2w3CImqrzLLYuB27PFD6DNdzdHX/view 

 

FAIR data principles for community centered data formats: https://www.nature.com/articles/s41597-022-01606-w  Research practices documents related to using data for equity - working with communities to find data to use in equity work, and how to best collect and use demographic (ethnic and racial equity, sexual orientation, and gender identity data, specifically). 

 

Article - Mapping for Whom? Communities of Color and the Citizen Science Gap: https://acme-journal.org/index.php/acme/article/view/2178/1654  

 

Global Indigenous Digital Alliance guidance on using CARE principles for Indigenous data governance: https://www.gida-global.org/care  

 

At the most basic level, taking an equity lens in Data Wise involves having a team ask itself probing questions at each step of the improvement process.  This document provides a look at how to use a data wise techniques with a racial equity lens.  https://www.ascd.org/el/articles/looking-at-data-through-an-equity-lens   

 

"collecting/using demographic data" - https://www.urban.org/sites/default/files/publication/103830/five-ethical-risks-to-consider-before-filling-missing-race-and-ethnicity-data-workshop-findings_0.pdf

**Comment by NMartorano** [comment]
Other State Examples 

City of Portland Racial Equity Toolkit: https://www.portlandoregon.gov/oehr/71685  

 

State of California Guidance 

Governor Executive Order on Racial Equity: https://www.gov.ca.gov/wp-content/uploads/2022/09/9.13.22-EO-N-16-22-Equity.pdf?emrc=c11513  

 

CalTrans: CONSIDERING EQUITY IN COMMUNITY IMPACT ANALYSIS FOR PROJECTS   https://dot.ca.gov/-/media/dot-media/programs/environmental-analysis/documents/ser/equity-guidance-a11y.pdf 

 

Document showing how a team at the Water Boards used last year’s Governor proposed budget (January budget) to derive challenge questions: https://docs.google.com/document/d/18kJKTQjR39_PhLLQXejKZcuZAY5sD4dFNpV9bfAtqKA/edit?usp=sharing 

 

OEHHA whitepaper on CalEnviroScreen 4.0 and how race and ethnicity is analyzed within that tool and the CES score correlations. 

https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40raceanalysisf2021.pdf 

(Internal at this point) CDFW and CNRA resource: [Web-based tools REPORT DRAFT 2.17.23.docx](https://cawaterboards-my.sharepoint.com/:w:/g/personal/greg_gearheart_waterboards_ca_gov/EZ9xso_GAI5OtkjKoZM-dtUBjljjPjFFvZz5txsWQUKpyA?e=5FOemo) 

 

Equity in the State Revolving Fund use for infrastructure:  https://www.policyinnovation.org/publications/a-fairer-funding-stream

**Comment by NMartorano** [comment]
Internal ORPP guidance on vulnerable communities  

[Vulnerable Communities FlowChart Brainstorm Draft 4.6.22 (1).docx](https://github.com/user-attachments/files/16605611/Vulnerable.Communities.FlowChart.Brainstorm.Draft.4.6.22.1.docx)

**Comment by NMartorano** [comment]
HiAP Workgroup of Strategic Growth Council report: "Identifying Governmental Public Health Systems Barriers and Facilitators to Complying with and Expanding Race 

and Ethnicity Data Disaggregation Standards"   
[RWJ-Croal-Data-Equity-FINAL-3-31-22 (1).pdf](https://github.com/user-attachments/files/16605625/RWJ-Croal-Data-Equity-FINAL-3-31-22.1.pdf)

**Comment by NMartorano** [comment]
Private Industry 

ESRI GIS Metadata guidance  
[Extend_the_Reach_of_Your_GIS (1).pdf](https://github.com/user-attachments/files/16605635/Extend_the_Reach_of_Your_GIS.1.pdf)

Additional [best practices from Esri](https://doc.arcgis.com/en/hub/content/prepare-your-content.htm#:~:text=Tags%E2%80%94These%20help%20users%20discover,facilitate%20their%20discovery%20and%20use.) on improving the quality of content within a Hub site.  Also worth noting that ArcGIS Online comes some general [categories](https://doc.arcgis.com/en/arcgis-online/reference/content-categories.htm) that are derived from ISO and INSPIRE.  Those could be good starting points, but my hunch is that you’re going to want to add additional categories to better support filtering and finding the right datasets. 

 

MN DOT Governance and Best Practices: A tailored document like this would be useful to encourage contributors to follow the same guidelines and understand which groups or tags need to be added for the data to be ingested properly.

[MnDOT Governance and Best Practices and User Requirements (1).docx](https://github.com/user-attachments/files/16605638/MnDOT.Governance.and.Best.Practices.and.User.Requirements.1.docx)

**Comment by NMartorano** [comment]
BEST PRACTICES Table
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/NMARTO~1/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/NMARTO~1/AppData/Local/Temp/1/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/NMARTO~1/AppData/Local/Temp/1/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#467886" vlink="#96607D" style='tab-interval:.5in;
word-wrap:break-word'>



Practice | Description | Source | Notes
-- | -- | -- | --
It is helpful to survey a range of existing tools when   considering the mapping of "disadvantaged" populations. | Each        presents strengths and weaknesses to consider while keeping in mind that        ultimately decisions will be driven by:     Statutory        mandates and priorities of each unique program      Data        availability, currency, longevity      Level        of spatial analysis appropriate for the program     Census        boundary (Tract, Block Group, or Block),       Project        radius (such as a half-mile),       Watershed,       Walkshed, | Web-based Tools for Identifying Underserved   Communities, CNRA | This guidance discusses things to consider when evaluating   tools and is applicable to work at the water boards too.
Users conducting an analysis with the CalEnviroScreen (CES) 4.0 dataset should be aware   that it contains missing values, both for individual indicators and overall   CES scores. | These missing values are distinct from zeros, which are   also in the CES dataset. For more information about the missing (and zero)   values, see the data dictionary   (calenviroscreen40resultsdatadictionary_F_2021.pdf) that accompanies   the CalEnviroScreen 4.0 results Excel workbook, available for   download as a zip file here. | Racial Equity Data Hub, Tools REDAP Resource Hub Draft (ca.gov), 6/2/2023. | Things to consider when using CalEnviroScreen Scores.
Utilizing quantitative and qualitative analyses to   identify inequities and response system  effectiveness. | Various national level quantitative and quantitative tools   exist to develop a continuum of care focusing on racial inequities and   homelessness.  Quantitative tools examine population data on race and   ethnicity and program outcomes data.  Qualitative tool include   interviewing people with lived experience. | Racial Equity Data Guidebook from the United States   Interagency Council on Homelessness: https://www.usich.gov/resources/uploads/asset_library/Racial_Equity_Data_Guidebook.pdf | Innovative tools when looking at homelessness and   race.  The tools could be used for other programs.
Using F.A.I.R. data principles | Four foundational principles—Findability, Accessibility,   Interoperability, and Reusability—that serve to guide data producers and   publishers in data management and stewarship. | Original principles from 2016 are available here: https://www.nature.com/articles/sdata201618 some   good documentation on how to operationalize FAIR principles for equity data   is available here: https://www.nature.com/articles/s41597-022-01606-w | Data management principles.
Using CARE principles for Indigenous Data governance. | The ‘CARE Principles for Indigenous Data Governance’   address concerns related to the people and purpose of data; Collective   benefit, Authority to control, Responsibility, and Ethics, and their   respective sub-principles.  The CARE Principles detail that the use   of Indigenous data should result in tangible benefits for Indigenous   collectives through inclusive development and innovation, improved governance   and citizen engagement, and result in equitable outcomes. | A good source of information on CARE including the   original publication is available here: https://www.gida-global.org/care        CARE and FAIR principles can go hand and hand and there is   good information on that available here: https://www.nature.com/articles/s41597-021-00892-0 | Data governance with a specific lens on tribal data and is   applicable to broader groups of underrepresented peoples.




</body>

</html>

**Comment by AHolder1** [comment]
@NMartorano - I am going to put each of the above comments into their own issues (so we can mark each thing as complete as we go and don't have to wait to add allll the things before we can mark this issue complete)

Once I've added a thing to it's own issue, I'll add a rocket emoji to the comment.

**Comment by AHolder1** [comment]
After each resources is pulled over into a GitHub issue - recommend change share settings so no one can view the link or add a note at the top of the OneNote stating that this is an old link and a more up to date version can be found
[here](https://cawaterboarddatacenter.github.io/equity-data-handbook/)...or maybe we just delete the OneNote altogether?

**Comment by NMartorano** [comment]
I think we could remove everyone's access to the One Note.  I found some other stuff that I cataloged specifically related to tools that I don't think made it to the resource hub but that would still be of value under our resources section, maybe have a subsection for tools.

Web Resources for Data and Tools<onenote:https://cawaterboards-my.sharepoint.com/personal/greg_gearheart_waterboards_ca_gov/Documents/REDAP%20Team%20Notes%20and%20Resources/Web%20Resources%20for%20Data%20and%20Tools.one#&section-id=90c6e03f-bc20-48e0-b4d9-efb8c453101b&end>  (Web view<https://cawaterboards-my.sharepoint.com/personal/greg_gearheart_waterboards_ca_gov/_layouts/15/Doc.aspx?sourcedoc=%7bb26ff2c3-af7e-4be5-b579-33ba46615b85%7d&action=edit&wd=target%28Web%20Resources%20for%20Data%20and%20Tools.one%7C90c6e03f-bc20-48e0-b4d9-efb8c453101b%2F%29&wdorigin=717&wdpreservelink=1>)


***@***.***

Nick Martorano
He/Him/His
Director, California Water Quality Monitoring Council
Office of Information Management and Analysis
State Water Resources Control Board
1001 I Street, Office 19-65A, Sacramento, CA 95814

Phone:      Office: (916) 341-5514 (voicemail to email) Email:       ***@***.******@***.***>
Website:  https://mywaterquality.ca.gov<http://mywaterquality.ca.gov/>
    "CONFIDENTIALITY NOTICE: This Communication, with its contents, may contain confidential and/or legally privileged
     information. It is solely for the use of the intended recipient(s). Unauthorized interception, review, use or disclosure is
     prohibited and may violate applicable laws, including the Electronic Communications Privacy Act. If you are not the
     intended recipient, please contact the sender and destroy all copies of the communication."

I respectfully acknowledge that we live and work on traditional, ancestral & unceded land of the Miwok<https://native-land.ca/maps/territories/plains-miwok/>, Patwin<https://native-land.ca/maps/territories/patwin/> and Nisenan<https://native-land.ca/maps/territories/nisenan/> nation. Whose land are you on?<https://urldefense.com/v3/__https://native-land.ca/__;!!Mih3wA!RY4Qv3WLTYK9Pr9FmJhtQbmjuGaYX_x5KT6bZtSxcFFQd1sgvBebjN8K3A6gAhVu$>

Learn about CalEPA's Commitment to Racial Equity<https://calepa.ca.gov/about/calepa-racial-equity-home/> and why we lead with race.
***@***.***

**Comment by AHolder1** [comment]
Perfect! I suspect many of these links will be ported over to our [Resources page](https://cawaterboarddatacenter.github.io/equity-data-handbook/resources.html) - and we can modify/create additional sections (e.g. tools) as appropriate. Or if the resource is a visualization tool, maybe we put it on the [data vis page](https://cawaterboarddatacenter.github.io/equity-data-handbook/vis.html)? Or both places!

**Comment by NMartorano** [comment]
I also pinged Allysen to make sure that she has captured most or all of those on the resources hub.


***@***.***

Nick Martorano
He/Him/His
Director, California Water Quality Monitoring Council
Office of Information Management and Analysis
State Water Resources Control Board
1001 I Street, Office 19-65A, Sacramento, CA 95814

Phone:      Office: (916) 341-5514 (voicemail to email) Email:       ***@***.******@***.***>
Website:  https://mywaterquality.ca.gov<http://mywaterquality.ca.gov/>
    "CONFIDENTIALITY NOTICE: This Communication, with its contents, may contain confidential and/or legally privileged
     information. It is solely for the use of the intended recipient(s). Unauthorized interception, review, use or disclosure is
     prohibited and may violate applicable laws, including the Electronic Communications Privacy Act. If you are not the
     intended recipient, please contact the sender and destroy all copies of the communication."

I respectfully acknowledge that we live and work on traditional, ancestral & unceded land of the Miwok<https://native-land.ca/maps/territories/plains-miwok/>, Patwin<https://native-land.ca/maps/territories/patwin/> and Nisenan<https://native-land.ca/maps/territories/nisenan/> nation. Whose land are you on?<https://urldefense.com/v3/__https://native-land.ca/__;!!Mih3wA!RY4Qv3WLTYK9Pr9FmJhtQbmjuGaYX_x5KT6bZtSxcFFQd1sgvBebjN8K3A6gAhVu$>

Learn about CalEPA's Commitment to Racial Equity<https://calepa.ca.gov/about/calepa-racial-equity-home/> and why we lead with race.
***@***.***
