### ISSUE TITLE
Add Water Board tools to Resources page

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/equity-data-handbook#26]
Water Board tools (existing or in the works) 

- [ ] The Water Conservation and Urban Water folks in ORPP built this tool: https://www.waterboards.ca.gov/water_issues/programs/conservation_portal/water-use-explorer/
- [ ] Racial Equity Workforce Planning (CalEPA) - [Practices to Advance Racial Equity in Workforce Plannin (ca.gov)](https://calepa.ca.gov/wp-content/uploads/sites/6/2021/11/Practices-to-Advance-Racial-Equity-in-Workforce-Planning.sw_.jh_.pdf?emrc=175a3b) 
- [ ] [Initial Proposals for Revising the Federal Race and Ethnicity Standards | OMB | The White House](https://www.whitehouse.gov/omb/briefing-room/2023/01/26/initial-proposals-for-revising-the-federal-race-and-ethnicity-standards/) 
- [ ] https://learn.arcgis.com/en/projects/create-a-social-equity-index-to-improve-public-health/  
- [ ] CalTrans Beta Equity Index Map:  https://caltrans.maps.arcgis.com/apps/webappviewer/index.html?id=8ff3d27cdc1a4e8da0ae09c6b076a253  
- [ ] SAFER Outreach Tool:  https://gispublic.waterboards.ca.gov/portal/apps/webappviewer/index.html?id=70d27423735e45d6b037b7fbaea9a6a6  
- [ ] ORPP Vulnerable Communities Platform: https://vcp-beta-1-1-gov-opr.hub.arcgis.com/
- [ ] GARE second survey results (see OneNote for files)

**Comment by NMartorano** [comment]
Added to Resources Page
