### ISSUE TITLE
Add new section here? -"what kinds of data are we talking about?"

### ISSUE THREAD

**Issue by ggearheart** [CAWaterBoardDataCenter/equity-data-handbook#37]
Am wondering if this is where we introduce the reader to "types of data" and the different responsibilities WB program staff when it comes to them. The types in mind are (1) administrative data (owned, stewarded by WB) and (2) other data. Each of these has sub types, sometimes common sub categories - demographics data, water quality, water resource, geospatial context, etc. The reason I want to add it early is to convey that step 1 for WB staff doing racial equity data work is to share their data as open data. Building a map before sharing the data is not the right order. Share the we have, then build a map showing what we think is interesting using that (and other) data. Etc.

**Comment by AHolder1** [comment]
Add a note at the top indicating the step 00 is making our data open and accessible - data not open yet? PUBLISH IT!....and here's how

**Comment by AHolder1** [comment]
@ggearheart - I am not sure where "here" is in reference to: "Add new section here?"

However, based on our conversation, I have made step 1 of the getting started guide to publish data. See: https://cawaterboarddatacenter.github.io/equity-data-handbook/get-started.html

We can also add a section before "Plan and Prepare" about "Publish Your Data" or "Make Data Open" (or something like that) to expand more - but if we do that, we'll want to go into more detail (which we totally can!) and provide more guidance than what already exists on the [open data handbook](https://www.waterboards.ca.gov/resources/oima/cowi/open_data_handbook.html). I think Rafa was working on writing up more specific guidance on how to publish data at the Water Boards - can we maybe incorporate that here?

Is that getting at what you were thinking?

**Comment by ggearheart** [comment]
Yes, this is great. @Kiran-Kaur90 is working on an overhaul of the Open Data Publication guide(s) and workflow, so when that is ready this handbook will point people to more comprehensive and detailed guidance. Thanks! I consider this done for now.

**Comment by AHolder1** [comment]
Awesome! I think I will still add a page on Publishing data to be explicit about why going through those steps helps advance equity / how to publish data with an equity lens. But I'll close this comment since your initial request has been met.

Maybe when @Kiran-Kaur90 is done creating the Open Data Publication guides - they can end up living in the [Open Data Handbook](https://www.waterboards.ca.gov/resources/oima/cowi/open_data_handbook.html)?

**Comment by ggearheart** [comment]
That's the plan!

Greg Gearheart (he/him)
Deputy Director, Office of Information Management and Analysis<https://www.waterboards.ca.gov/resources/oima/>
CA Water Boards / CalEPA
(916) 341-5892 (voice mail forwards to my email)




________________________________

**Comment by AHolder1** [comment]
OK - general page is drafted. https://cawaterboarddatacenter.github.io/equity-data-handbook/publish-data.html
I kept it pretty high level and welcome any recommendations for improvement by @ggearheart and @Kiran-Kaur90 , particularly as you develop the more thorough guidance.

**Comment by AHolder1** [comment]
OK - general page is drafted. https://cawaterboarddatacenter.github.io/equity-data-handbook/publish-data.html
I kept it pretty high level and welcome any recommendations for improvement by @ggearheart and @Kiran-Kaur90 , particularly as you develop the more thorough guidance.
