### ISSUE TITLE
Decide where to put Openscapes content

### ISSUE THREAD

**Issue by esuglia** [CAWaterBoardDataCenter/equity-data-handbook#38]
Getting started? Best Practices? Started discussion during 8/27 cowork session. @esuglia could draft some content.

**Comment by AHolder1** [comment]
After thinking about this a bit more, I think adding to the Getting Started page as an optional but recommended item is the best place (at least for now). See https://cawaterboarddatacenter.github.io/equity-data-handbook/get-started/

We can revise/add/discuss more during the review process, but for now I'm going to close this issue.
