### ISSUE TITLE
Discuss / set up Handbook feedback process

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/equity-data-handbook#45]
Current feedback instructions on [welcome page](https://cawaterboarddatacenter.github.io/equity-data-handbook/): 
If you have suggestions for additions or revisions you think should be incorporated into this book, please email [equitydatahelp@waterboards.ca.gov](mailto:equitydatahelp@waterboards.ca.gov).

Do we want to set up some sort of form where people can submit feedback? Or describe how to submit issues? Both? Something else? 

Inspiration: 

- Tribal Water Data Map [Contributing Page](https://cawaterboarddatacenter.github.io/tribal-water-data-map-manual/contribute.html)
- SWAMP Manual [Contributing Page](https://cawaterboarddatacenter.github.io/swamp-manual/contribute.html)

**Comment by DevanBurke** [comment]
We could mimic a process done with some of the other RE documents developed at the WB. For example, use a spreadsheet to track feedback and color code based on: (1) Whether the feedback was incorporated, (2) Was not incorporated, (3) Not relevant) and a column to describe why it was or was not included.
